/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codfiscale;

/**
 *
 * @author Alessandra
 */

public class GUIfiscale extends javax.swing.JFrame {

    /**
     * Creates new form GUIfiscale
     */
    public GUIfiscale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jRadioButton1 = new javax.swing.JRadioButton();
        maschio = new javax.swing.JRadioButton();
        result = new javax.swing.JTextField();
        Label1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        cognome = new javax.swing.JTextField();
        anno = new javax.swing.JTextField();
        luogo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        giorno = new javax.swing.JTextField();
        mese = new javax.swing.JTextField();
        ComboSesso = new javax.swing.JComboBox<>();

        jRadioButton1.setText("Femmina");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        maschio.setText("Maschio");
        maschio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maschioActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        result.setEditable(false);
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        Label1.setText("Result");

        luogo.setEditable(false);
        luogo.setText("Roma");
        luogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luogoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Cognome");

        jLabel3.setText("giorno");

        jLabel4.setText("mese");

        jLabel5.setText("anno");

        jLabel6.setText("luogo");

        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        giorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giornoActionPerformed(evt);
            }
        });

        ComboSesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maschio", "Femmina" }));
        ComboSesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSessoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luogo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel4))
                            .addComponent(jLabel1)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(giorno, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mese)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(Label1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(calculate))
                                .addComponent(cognome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ComboSesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(anno, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel6))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(giorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mese, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboSesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label1)
                    .addComponent(calculate))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultActionPerformed

    private void luogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luogoActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        String name = nome.getText();
        String sesso = ComboSesso.getSelectedItem().toString();
        char name1[] = name.toCharArray();
        String surname = cognome.getText();
        char surname1[] = surname.toCharArray();
        int day = Integer.parseInt(giorno.getText());
        String day1 = giorno.getText();
        String month = mese.getText();
        String year = anno.getText();
        String subyear = year.substring(2, 4);
        String consonanti = "bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ";
        String vocali = "aeiouAEIOU";
        char vocali2[] = vocali.toCharArray();
        char consonanti2[] = consonanti.toCharArray();
        String fine = "";
        
        for(int i = 0; i < surname.length(); i++ ){
            for(int j = 0; j < consonanti.length(); j++){
                if(surname1[i] == consonanti2[j]){
                    if(fine.length() == 3){
                        break;
                    }
                    fine = fine + Character.toUpperCase(consonanti2[j]);
                }
            }
        }
        if(fine.length() < 3){
            for(int i = 0; i < surname.length(); i++){
                for(int j = 0; j < vocali.length(); j++){
                    if(surname1[i] == vocali2[j]){
                        fine = fine + Character.toUpperCase(vocali2[j]);
                        j = vocali.length();
                        i = surname.length();
                    }
                }
            }
        }
        
        for(int i = 0; i < name.length(); i++ ){
            for(int j = 0; j < consonanti.length(); j++){
                if(name1[i] == consonanti2[j]){
                    if(fine.length() == 6){
                        break;
                    }
                    fine = fine + Character.toUpperCase(consonanti2[j]);
                }
            }
        }
        if(fine.length() < 6){
            for(int i = 0; i < name.length(); i++){
                for(int j = 0; j < vocali.length(); j++){
                    if(name1[i] == vocali2[j]){
                        fine = fine + Character.toUpperCase(vocali2[j]);
                        j = vocali.length();
                        i = surname.length();
                    }
                }
            }
        }
        
        fine = fine+subyear;
        
        if(month.equals("Gennaio") || month.equals("gennaio")){
            fine = fine+"A";
        }
        if(month.equals("Febbraio") || month.equals("febbraio")){
            fine = fine+"B";
        }
        if(month.equals("Marzo") || month.equals("marzo")){
            fine = fine+"C";
        }
        if(month.equals("Aprile") || month.equals("aprile")){
            fine = fine+"D";
        }
        if(month.equals("Maggio") || month.equals("maggio")){
            fine = fine+"E";
        }
        if(month.equals("Giugno") || month.equals("giugno")){
            fine = fine+"H";
        }
        if(month.equals("Luglio") || month.equals("luglio")){
            fine = fine+"L";
        }
        if(month.equals("Agosto") || month.equals("agosto")){
            fine = fine+"M";
        }
        if(month.equals("Settembre") || month.equals("settembre")){
            fine = fine+"P";
        }
        if(month.equals("Ottobre") || month.equals("ottobre")){
            fine = fine+"R";
        }
        if(month.equals("Novembre") || month.equals("novembre")){
            fine = fine+"S";
        }
        if(month.equals("Dicembre") || month.equals("dicembre")){
            fine = fine+"T";
        }
        
        String giorni[] = new String[31];
        for(int i = 0; i < 31; i++){
            giorni[i] = ""+i;
            if(day1.equals("0"+giorni[i])){
                if(sesso.equals("Femmina")){
                    day = Integer.parseInt(day1)+40;
                    fine = fine+day;
                }
                else{
                    fine = fine+day1;
                }
            }
            if(giorni[i].equals(day1)){
                
                if(sesso.equals("Femmina")){
                    day = Integer.parseInt(day1)+40;
                    fine = fine+day;
                }
                else{
                    if(day < 10){
                        day1="0"+day1;
                    }
                    fine = fine+day1;
                }
            }  
        }
        if(sesso.equals("Femmina")){
            
        }
        
        fine = fine+"H501";
        
        char ffine[] = fine.toCharArray();
        int valore = 0;
        
        for(int i = 1; i < fine.length(); i=i+2){
            switch(ffine[i]){
                case 'A':
                    valore+=1;
                    break;
                case '0':
                    valore+=1;
                    break;
                case 'B':
                    valore+=0;
                    break;
                case '1':
                    valore+=0;
                    break;
                case 'C':
                    valore+=5;
                    break;
                case '2':
                    valore+=5;
                    break;
                case 'D':
                    valore+=7;
                    break;
                case '3':
                    valore+=7;
                    break;
                case 'E':
                    valore+=9;
                    break;
                case '4':
                    valore+=9;
                    break;
                case 'F':
                    valore+=13;
                    break;
                case '5':
                    valore+=13;
                    break;
                case 'G':
                    valore+=15;
                    break;
                case '6':
                    valore+=15;
                    break;
                case 'H':
                    valore+=17;
                    break;
                case '7':
                    valore+=17;
                    break;
                case 'I':
                    valore+=19;
                    break;
                case '8':
                    valore+=19;
                    break;
                case 'J':
                    valore+=21;
                    break;
                case '9':
                    valore+=21;
                    break;
                case 'K':
                    valore+=2;
                    break;
                case 'L':
                    valore+=4;
                    break;
                case 'M':
                    valore+=18;
                    break;
                case 'N':
                    valore+=20;
                    break;
                case 'O':
                    valore+=11;
                    break;
                case 'P':
                    valore+=3;
                    break;
                case 'Q':
                    valore+=6;
                    break;
                case 'R':
                    valore+=8;
                    break;
                case 'S':
                    valore+=12;
                    break;
                case 'T':
                    valore+=14;
                    break;
                case 'U':
                    valore+=16;
                    break;
                case 'V':
                    valore +=10;
                    break;
                case 'W':
                    valore+=22;
                    break;
                case 'X':
                    valore+=25;
                    break;
                case 'Y':
                    valore+=24;
                    break;
                case 'Z':
                    valore+=23;
                    break;
            }
        }
        
        for(int i = 0; i <= fine.length(); i=i+2){
            switch(ffine[i]){
                case 'A':
                    valore+=0;
                    break;
                case '0':
                    valore+=0;
                    break;
                case 'B':
                    valore+=1;
                    break;
                case '1':
                    valore+=1;
                    break;
                case 'C':
                    valore+=2;
                    break;
                case '2':
                    valore+=2;
                    break;
                case 'D':
                    valore+=3;
                    break;
                case '3':
                    valore+=3;
                    break;
                case 'E':
                    valore+=4;
                    break;
                case '4':
                    valore+=4;
                    break;
                case 'F':
                    valore+=5;
                    break;
                case '5':
                    valore+=5;
                    break;
                case 'G':
                    valore+=6;
                    break;
                case '6':
                    valore+=6;
                    break;
                case 'H':
                    valore+=7;
                    break;
                case '7':
                    valore+=7;
                    break;
                case 'I':
                    valore+=8;
                    break;
                case '8':
                    valore+=8;
                    break;
                case 'J':
                    valore+=9;
                    break;
                case '9':
                    valore+=9;
                    break;
                case 'K':
                    valore+=10;
                    break;
                case 'L':
                    valore+=11;
                    break;
                case 'M':
                    valore+=12;
                    break;
                case 'N':
                    valore+=13;
                    break;
                case 'O':
                    valore+=14;
                    break;
                case 'P':
                    valore+=15;
                    break;
                case 'Q':
                    valore+=16;
                    break;
                case 'R':
                    valore+=17;
                    break;
                case 'S':
                    valore+=18;
                    break;
                case 'T':
                    valore+=19;
                    break;
                case 'U':
                    valore+=20;
                    break;
                case 'V':
                    valore +=21;
                    break;
                case 'W':
                    valore+=22;
                    break;
                case 'X':
                    valore+=23;
                    break;
                case 'Y':
                    valore+=24;
                    break;
                case 'Z':
                    valore+=25;
                    break;
            }
            
        }
        valore = valore % 26;
        
        switch(valore){
                case 0:
                    fine= fine+'A';
                    break;
                case 1:
                    fine= fine+'B';
                    break;
                case 2:
                    fine= fine+'C';
                    break;
                case 3:
                    fine= fine+'D';
                    break;
                case 4:
                    fine= fine+'E';
                    break;
                case 5:
                    fine= fine+'F';
                    break;
                case 6:
                    fine= fine+'G';
                    break;
                case 7:
                    fine= fine+'H';
                    break;
                case 8:
                    fine= fine+'I';
                    break;
                case 9:
                    fine= fine+'J';
                    break;
                case 10:
                    fine= fine+'K';
                    break;
                case 11:
                    fine= fine+'L';
                    break;
                case 12:
                    fine= fine+'M';
                    break;
                case 13:
                    fine= fine+'N';
                    break;
                case 14:
                    fine= fine+'O';
                    break;
                case 15:
                    fine= fine+'P';
                    break;
                case 16:
                    fine= fine+'Q';
                    break;
                case 17:
                    fine= fine+'R';
                    break;
                case 18:
                    fine= fine+'S';
                    break;
                case 19:
                    fine= fine+'T';
                    break;
                case 20:
                    fine= fine+'U';
                    break;
                case 21:
                    fine= fine+'V';
                    break;
                case 22:
                    fine= fine+'W';
                    break;
                case 23:
                    fine= fine+'X';
                    break;
                case 24:
                    fine= fine+'Y';
                    break;
                case 25:
                    fine= fine+'Z';
                    break;
                
            }
        result.setText(fine);
        
    }//GEN-LAST:event_calculateActionPerformed

    private void giornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giornoActionPerformed

    private void maschioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maschioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maschioActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void ComboSessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIfiscale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIfiscale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIfiscale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIfiscale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIfiscale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboSesso;
    private javax.swing.JLabel Label1;
    private javax.swing.JTextField anno;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField cognome;
    private javax.swing.JTextField giorno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField luogo;
    private javax.swing.JRadioButton maschio;
    private javax.swing.JTextField mese;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
